// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PodcastTranscription.Web.Data;

#nullable disable

namespace PodcastTranscription.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906024710_TranscriptQualityWarning")]
    partial class TranscriptQualityWarning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DurationSec")
                        .HasColumnType("REAL");

                    b.Property<int?>("FeedId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedItemGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparedAudioPath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Show")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudioSha256");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FeedId", "FeedItemGuid");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoTranscribe")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastPolledAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RssUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RssUrl")
                        .IsUnique();

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChunkPlanJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedChunks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProcessedAudioSec")
                        .HasColumnType("REAL");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TranscriptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("TranscriptId");

                    b.HasIndex("State", "CreatedAt");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgLogProb")
                        .HasColumnType("REAL");

                    b.Property<int>("EndMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TranscriptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WordsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranscriptId", "Ordinal")
                        .IsUnique();

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Transcript", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityWarning")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RealtimeFactor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Transcripts");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.TranscriptChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranscriptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TranscriptId", "Index")
                        .IsUnique();

                    b.ToTable("TranscriptChunks");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Episode", b =>
                {
                    b.HasOne("PodcastTranscription.Web.Domain.Feed", "Feed")
                        .WithMany("Episodes")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Job", b =>
                {
                    b.HasOne("PodcastTranscription.Web.Domain.Episode", "Episode")
                        .WithMany("Jobs")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PodcastTranscription.Web.Domain.Transcript", "Transcript")
                        .WithMany()
                        .HasForeignKey("TranscriptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Episode");

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Segment", b =>
                {
                    b.HasOne("PodcastTranscription.Web.Domain.Transcript", "Transcript")
                        .WithMany("Segments")
                        .HasForeignKey("TranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Transcript", b =>
                {
                    b.HasOne("PodcastTranscription.Web.Domain.Episode", "Episode")
                        .WithMany("Transcripts")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.TranscriptChunk", b =>
                {
                    b.HasOne("PodcastTranscription.Web.Domain.Transcript", "Transcript")
                        .WithMany("Chunks")
                        .HasForeignKey("TranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Episode", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Transcripts");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Feed", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("PodcastTranscription.Web.Domain.Transcript", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
